# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'smack-slack-clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for smack-slack-clone
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Socket.IO-Client-Swift'

  target 'smack-slack-cloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'smack-slack-cloneUITests' do
    # Pods for testing
  end

end
